name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Move to backend folder
          cd backend
          
          # 2. Initialize a fresh Git repository
          git init -b main
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          # 3. Add files and commit
          git add .
          git commit -m "Deploy to Hugging Face Spaces"
          
          # 4. Force push to Hugging Face
          git push https://tonybnya:$HF_TOKEN@huggingface.co/spaces/tonybnya/paylite-backend main --force
