name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure Git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # 1. Create a temporary branch containing only the backend folder
          git subtree split --prefix backend -b deploy-branch
          
          # 2. Force push the temporary branch to Hugging Face
          # This ensures that even if Hugging Face has a default README.md, our code overwrites it.
          git push https://tonybnya:$HF_TOKEN@huggingface.co/spaces/tonybnya/paylite-backend deploy-branch:main --force
